/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f407xx.h"

#define USART2EN		(1U << 17)
#define GPIOAEN			(1U << 0)
#define CR1_TE			(1U << 3)
#define CR1_UE			(1U << 13)
#define SR_TXE			(1U << 7)

#define SYS_FREQ		16000000
#define APB1_CLK		SYS_FREQ
#define UART_BAUDRATE	9600

/*
 * PA0 - USART2_CTS
 * PA1 - USART2_RTS
 * PA2 - USART2_TX
 * PA3 - USART2_RX
 * PA4 - USART2_CK
 *
 * USART registers:
 * 	Status      - USART_SR
 * 	Data        - USART_DR
 * 	Baud rate   - USART_BRR
 * 	Control 1   - USART_CR1 : has the TX, RX etc bits to set
 * */

void uart2_tx_init(void);
void uart2_rx_init(void);
void uart2_write(int ch);

static void uart_set_baudrate(USART_TypeDef *USARTx, uint32_t PeriphClk, uint32_t BaudRate);
static uint16_t compute_uart_bd(uint32_t PeriphClk, uint32_t BaudRate);

/************************************************* */
/* MAIN */
/************************************************* */
int main(void)
{
    uart2_tx_init();

    while(1)
    {
        uart2_write('Y');

		for(int i=0; i < 100000; i++) {
			__asm__ volatile ("nop");
		}
    }
}

/****************************************************************/
/* UART2 TX INIT */
/****************************************************************/
void uart2_tx_init(void)
{
	/*********** Configure UART GPIO PIN ************/
	/* Enable clock access to GPIOA */
	RCC->AHB1ENR |= GPIOAEN;

	/* Set PA2 Mode to alternate function mode */
	GPIOA->MODER |=  (1U << 5);
	GPIOA->MODER &= ~(1U << 4);

	/* Set PA2 alternate function type to UART TX (AF07) */
	GPIOA->AFR[0] |= (0x07 << (4 * 2));

	/*********** Configure UART Module ************/
	/* Enable clock access to UART2 */
	RCC->APB1ENR |= USART2EN;

	/* Configure baudrate */
	uart_set_baudrate(USART2, APB1_CLK, UART_BAUDRATE);

	/* Configure transfer direction, enables the TX */
	USART2->CR1 = CR1_TE;  // We want to clear everything when enabling so no |=
	/* Enable UART Module */
	USART2->CR1 |= CR1_UE;
}

/****************************************************************/
/* UART WRITE */
/****************************************************************/
void uart2_write(int ch)
{
	/* Ensure transmit data register is empty TXE */
    // & allows you to read bit, returns true while it is enabled
    while(!(USART2->SR & SR_TXE)){}
	/* Write to transmit data register */
	USART2->DR = (ch & 0xFF);
}

/****************************************************************/
/* UART SET BAUDRATE */
/****************************************************************/
static void uart_set_baudrate(USART_TypeDef *USARTx, uint32_t PeriphClk, uint32_t BaudRate)
{
	USARTx->BRR = compute_uart_bd(PeriphClk, BaudRate);
}

/****************************************************************/
/* COMPUTE UART BD */
/****************************************************************/
static uint16_t compute_uart_bd(uint32_t PeriphClk, uint32_t BaudRate)
{
	return ((PeriphClk + (BaudRate / 2U)) / BaudRate);
}
