/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f407xx.h"

#define USART2EN		(1U << 17)
#define GPIOAEN			(1U << 0)
#define GPIODEN			(1U << 3)

#define CR1_TE			(1U << 3)
#define SR_TC			(1U << 6)
#define SR_TXE			(1U << 7)
#define CR1_UE			(1U << 13)

#define SYS_FREQ		16000000
#define APB1_CLK		SYS_FREQ
#define UART_BAUDRATE	9600

#define TX_DONE_LED    		12 	// GREEN
#define TX_READY_LED   		13	// ORANGE
#define TX_BUSY_LED    		14	// RED
#define LED15  				15  // BLUE
#define CLR_DONE  			28
#define CLR_READY			29
#define CLR_BUSY			30
#define LED_PINS_MODER  ((1U << (2U * TX_DONE_LED))  | \
                         (1U << (2U * TX_READY_LED)) | \
                         (1U << (2U * TX_BUSY_LED))  | \
                         (1U << (2U * LED15)))

#define LED_MODER_MASK  ((3U << (2U * TX_DONE_LED))  | \
                         (3U << (2U * TX_READY_LED)) | \
                         (3U << (2U * TX_BUSY_LED))  | \
                         (3U << (2U * LED15)))


/*
 * PA0 - USART2_CTS
 * PA1 - USART2_RTS
 * PA2 - USART2_TX
 * PA3 - USART2_RX
 * PA4 - USART2_CK
 *
 * USART registers:
 * 	Status      - USART_SR
 * 	Data        - USART_DR
 * 	Baud rate   - USART_BRR
 * 	Control 1   - USART_CR1 : has the TX, RX etc bits to set
 * 
 * TXE: [Transmit data register empty]: 
 */

void uart2_tx_init(void);
void uart2_rx_init(void);
void uart2_write(int ch);
void txe_confirm(void);

void gpiod_init(void);
void busy_wait(void);

static void uart_set_baudrate(USART_TypeDef *USARTx, uint32_t PeriphClk, uint32_t BaudRate);
static uint16_t compute_uart_bd(uint32_t PeriphClk, uint32_t BaudRate);
int __io_putchar(int ch);

/************************************************* */
/* MAIN */
/************************************************* */
int main(void)
{
	GPIOD->BSRR = (1U << CLR_DONE);
	busy_wait();
    uart2_tx_init();
	gpiod_init();

    while(1)
    {
        uart2_write('Y');
		busy_wait();
    }
}

/****************************************************************/
/* GPIOD INIT */
/****************************************************************/
void gpiod_init(void)
{
	/* Enable clock access to GPIOD */
	RCC->AHB1ENR |= GPIODEN;

	// Same as 0x04 on a 32bit reg
	GPIOD->MODER &= ~LED_MODER_MASK;
	GPIOD->MODER |= LED_PINS_MODER;

	// Set for high speed
	GPIOD->OSPEEDR |= (1U << 27);
	GPIOD->OSPEEDR &= ~(1U << 26);
}

/****************************************************************/
/* UART2 TX INIT */
/****************************************************************/
void uart2_tx_init(void)
{
	/*********** Configure UART GPIO PIN ************/
	/* Enable clock access to GPIOA */
	RCC->AHB1ENR |= GPIOAEN;

	/* Set PA2 Mode to alternate function mode */
	GPIOA->MODER |=  (1U << 5);
	GPIOA->MODER &= ~(1U << 4);

	/* Set PA2 alternate function type to UART TX (AF07) */
	GPIOA->AFR[0] |= (0x07 << (4 * 2));

	/*********** Configure UART Module ************/
	/* Enable clock access to UART2 */
	RCC->APB1ENR |= USART2EN;

	/* Configure baudrate */
	uart_set_baudrate(USART2, APB1_CLK, UART_BAUDRATE);

	/* Configure transfer direction, enables the TX */
	USART2->CR1 = CR1_TE;  // We want to clear everything when enabling so no |=
	/* Enable UART Module */
	USART2->CR1 |= CR1_UE;
}

/****************************************************************/
/* UART WRITE */
/****************************************************************/
void uart2_write(int ch)
{
    while (!(USART2->SR & SR_TXE)) {
        GPIOD->BSRR = (1U << CLR_READY);
        GPIOD->BSRR = (1U << CLR_DONE);
        GPIOD->BSRR = (1U << TX_BUSY_LED);
    }

    GPIOD->BSRR = (1U << CLR_BUSY);
    GPIOD->BSRR = (1U << CLR_DONE);
    GPIOD->BSRR = (1U << TX_READY_LED);

    USART2->DR = (ch & 0xFF);

    while (!(USART2->SR & SR_TC)) {
        GPIOD->BSRR = (1U << CLR_READY);
        GPIOD->BSRR = (1U << TX_BUSY_LED);
    }

    GPIOD->BSRR = (1U << CLR_READY);
    GPIOD->BSRR = (1U << CLR_BUSY);
    GPIOD->BSRR = (1U << TX_DONE_LED);
}

/****************************************************************/
/* UART SET BAUDRATE */
/****************************************************************/
static void uart_set_baudrate(USART_TypeDef *USARTx, uint32_t PeriphClk, uint32_t BaudRate)
{
	USARTx->BRR = compute_uart_bd(PeriphClk, BaudRate);
}

/****************************************************************/
/* COMPUTE UART BD */
/****************************************************************/
static uint16_t compute_uart_bd(uint32_t PeriphClk, uint32_t BaudRate)
{
	return ((PeriphClk + (BaudRate / 2U)) / BaudRate);
}

/****************************************************************/
/* IO PUTCHAR */
/****************************************************************/
int __io_putchar(int ch)
{
	uart2_write(ch);
	return ch;
}

/****************************************************************/
/* ASM NOP BUSY WAIT */
/****************************************************************/
void busy_wait(void)
{
	for(int i=0; i < 100000; i++) {
		__asm__ volatile ("nop");
	}
}